name: Random Repo Activities

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual trigger

jobs:
  auto-activities:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.FINE_GRAINED_PAT }}
        fetch-depth: 0

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Create and run activity script
      id: activity
      run: |
        cat > activity_script.py << EOL
        # ... [Previous Python script remains unchanged] ...
        EOL

        output=$(python activity_script.py)
        echo "$output" >> $GITHUB_OUTPUT

    - name: Commit changes
      if: steps.activity.outputs.ACTIVITY == 'commit'
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add commit_data.txt activity_log.txt
        git commit -m "Auto activity: Commit at $(date -u)"
        git push

    - name: Create Pull Request
      if: steps.activity.outputs.ACTIVITY == 'pr'
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        branch_name="auto-pr-$(date +%s)"
        git checkout -b $branch_name
        echo "This is an auto-generated PR at $(date -u)" >> auto_pr_file.txt
        git add auto_pr_file.txt
        git commit -m "Auto activity: Create PR at $(date -u)"
        git push --set-upstream origin $branch_name
        gh pr create --title "Auto PR: $(date -u)" --body "This is an automatically generated Pull Request." --head $branch_name
      env:
        GH_TOKEN: ${{ secrets.FINE_GRAINED_PAT }}

    - name: Create Issue
      if: steps.activity.outputs.ACTIVITY == 'issue'
      run: |
        gh issue create --title "Auto Issue: $(date -u)" --body "This is an automatically generated Issue."
      env:
        GH_TOKEN: ${{ secrets.FINE_GRAINED_PAT }}
